<?php
/**
 * @file
 * This file contains all the dic hook implementations.
 */

/**
 * Implements hook_menu().
 */
function dic_menu() {
  $items = array();

  $items['admin/config/system/dic'] = array(
    'title' => 'Dependency Injection Container',
    'description' => 'Dependency Injection Container settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dic_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/dic.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_admin_menu_cache_info().
 */
function dic_admin_menu_cache_info() {
  $caches['dic'] = array(
    'title' => t('Dependency Injection Container'),
    'callback' => 'dic_clear_container_cache',
  );

  return $caches;
}

/**
 * Implements hook_modules_enabled().
 */
function dic_modules_enabled($modules) {
  dic_clear_container_cache();
}

/**
 * Implements hook_modules_disabled().
 */
function dic_modules_disabled($modules) {
  dic_clear_container_cache();
}

/**
 * Clear the Dependency Injection Container.
 */
function dic_clear_container_cache() {
  $container_path = drupal_realpath('public://') . '/.container/container.php';
  if (file_exists($container_path)) {
    unlink($container_path);
  }
}

/**
 * Add the configured settings to the composer.json file.
 *
 * @param array $json
 */
function dic_composer_json_alter(&$json) {
  $json['require'] = array_merge(variable_get('dic_require', array()), $json['require']);

  foreach (variable_get('dic_repositories', array()) as $type => $url) {
    $json['repositories'][] = array(
      'type' => $type,
      'url' => $url,
    );
  }

  foreach (variable_get('dic_installer_paths', array()) as $path => $property) {
    $json['extra']['installer-paths'][$path] = $property;
  }
}
