<?php
/**
 * @file
 * This file contains all the dic_cm hook implementations.
 */

/**
 * Implements hook_menu().
 */
function dic_cm_menu() {
  $items = array();

  $items['admin/config/system/dic'] = array(
    'title' => 'Dependency Injection Container',
    'description' => 'Dependency Injection Container settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dic_cm_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/dic_cm.admin.inc',
  );

  return $items;
}

/**
 * Add the configured settings to the composer.json file.
 *
 * @param array $json
 */
function dic_cm_composer_json_alter(&$json) {
  $json['require'] = array_merge(variable_get('dic_cm_require', array()), $json['require']);

  foreach (variable_get('dic_cm_repositories', array()) as $type => $url) {
    $json['repositories'][] = array(
      'type' => $type,
      'url' => $url,
    );
  }

  foreach (variable_get('dic_cm_installer_paths', array()) as $path => $property) {
    $json['extra']['installer-paths'][$path] = array($property);
  }
}